# Generated by Django 5.1.3 on 2024-11-20 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('expiration_date', models.DateTimeField()),
                ('unique_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expiration_date', 'unique_link'], name='myapp_fileu_expirat_388c0a_idx')],
            },
        ),
    ]
