# Generated by Django 5.1.3 on 2024-11-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
